 export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST' 

 export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS' 
 
 export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE' 


 export const GET_GINGLE_PRODUCT_REQUEST = 'GET_GINGLE_PRODUCT_REQUEST' 

 export const GET_GINGLE_PRODUCT_SUCCESS = 'GET_GINGLE_PRODUCT_SUCCESS' 
 
 export const GET_GINGLE_PRODUCT_FAILURE = 'GET_GINGLE_PRODUCT_FAILURE' 